### ISSUE TITLE
Cache expiration value to be driven from config

### ISSUE THREAD

**Issue by richardimaoka** [builderscon/octav#193]
こういうコードが色々なところにあるので、

```
var cacheMiss bool
_, err = c.GetOrSet(key, &r, func() (interface{}, error) {
  //...
}, cache.WithExpires(time.Hour))
```

`cache.WithExpires()`に渡す値はConfigで指定できると良いかと思います。
例えば開発環境はキャッシュの時間を短くするかゼロにして、変更がすぐに反映されるように。

**Comment by richardimaoka** [comment]
あ、そういえばこれどこかで「データベース側が更新されたらプッシュ方式でキャッシュを更新したい」という話が出ていたんでしたっけ？

まあ、でもexpiryの値はconfigで指定できた方が良いと思っています。

**Comment by lestrrat** [comment]
機能的にはあってもいいですけど、開発環境はredisに入って keys コマンドでキーを抽出して消せばいいだけなので大分プライオリティは低いと思います。

あといくつか考える事：
* 全部のキャッシュが同じExpiresを持つように設定するのか？
* 一個一個の値が違う場合、逆にどこまで設定を変えると反映されるようにするのか？
* CACHE_EXPIRES_CONFERENCE=3600, CACHE_EXPIRES_SESSION=300, とか増やすの？
* 運用してるときに逆にどの設定がどのキャッシュに適用されているのかわかりにくくならない？

**Comment by richardimaoka** [comment]
なるほど、それならプライオリティは低いですね。

で、開発環境でさえ変える必要がないなら、基本一つしかサービスのインスタンスがない(フレームワーク的に同じコード、違うconfigでいろんな人が違うサービスを立てない)のでConfigにするメリットがほとんどない気がしてきました。

**Comment by richardimaoka** [comment]
Closeします。後で気になったらまたreopenすればよいとおもいます。ありがとうございました。
