### ISSUE TITLE
Fix the certificates

### ISSUE THREAD

**Issue by lestrrat** [builderscon/octav#62]
For whatever reason, admin.builderscon.io's certficates are currently ["not trusted"](https://www.ssllabs.com/ssltest/analyze.html?d=admin.builderscon.io)

Certificate generation is done via [go-cloud-acmeagent](https://github.com/lestrrat/go-cloud-acmeagent), somewhere around [here](https://github.com/lestrrat/go-cloud-acmeagent/blob/master/gcp/store.go#L224). Keys are uploaded to Kubernetes secrets around [here](https://github.com/lestrrat/go-cloud-acmeagent/blob/master/gcp/ssl.go#L24)

**Comment by uzulla** [comment]
I doubt this line.
https://github.com/lestrrat/go-cloud-acmeagent/blob/b75f13628a73d7c436177c61696bd8d4d23162de/interface.go#L19
